services:
  - type: web
    name: ciso-assistant-community
    env: docker
    dockerComposePath: docker-compose.yml
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_ALLOWED_HOSTS
        value: "0.0.0.0"
